# Use the official Node.js image based on Debian
#FROM node:18
FROM node:18-alpine AS build


# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port (change as per your app, e.g., 3000)
EXPOSE 3001

# Set environment variables (optional, customize as needed)
# ENV NODE_ENV=production
# ENV MONGO_URI=mongodb://your-mongo-uri

# Start the application
CMD ["npm", "start"]
